const DEPTH = {
    BACKGROUND: 0,
    GAMEPLAY: 5,
    GRIDBALL: 6,
    FALLBALL: 7,
    TAIL: 8,
    BULLET: 10,
    PARTICLE:11,
    HOLES: 12,
    ANIMATIONEXPLODE: 13,
    ANIMATIONBOMBEXPLODE: 14,
    FIREBALL: 15,
    HUDCONTAINER: 15,
    LIGHT:16,
    ICON: 16,
    TEXT:17,
    GAMEOVERCONTAINER:18
}

export default DEPTH;